# EDA NOTEBOOK LIMPIEZA_DATOS

* Install pandas
* Import pandas as pd
* Load dataset "adult.csv"

In [86]:
!pip install pandas


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [87]:
# import pandas
# import numpy
# load dataset
import pandas as pd
import numpy as np
pd.options.mode.copy_on_write

False

In [88]:
df_adult = pd.read_csv("../data/adult.csv")

In [89]:
# Creamos una copia del dataset 
df = df_adult

In [90]:
# tamaño del dataset
df.shape

(32561, 15)

In [91]:
# miramos info inicial del dataset( columnas, types etc.)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [92]:
# miramos una muestra del dataset (10 filas)
df.sample(10)

age         workclass  fnlwgt     education  education.num  \
22055   64  Self-emp-not-inc  352712     Assoc-voc             11   
11786   34           Private   40067  Some-college             10   
27734   21           Private  119704  Some-college             10   
7661    25           Private  109009          11th              7   
25252   28           Private  165030  Some-college             10   
29819   21           Private  265356  Some-college             10   
31110   18           Private  174926           9th              5   
15732   20           Private  691830       HS-grad              9   
1674    43      Self-emp-inc   62026   Prof-school             15   
15695   43           Private  347653  Some-college             10   

           marital.status       occupation    relationship   race     sex  \
22055  Married-civ-spouse  Farming-fishing         Husband  White    Male   
11786  Married-civ-spouse     Craft-repair         Husband  White    Male   
27734       Never-married            Sales       Unmarried  White  Female   
7661   Married-civ-spouse     Craft-repair         Husband  White    Male   
25252       Never-married  Exec-managerial   Not-in-family  White  Female   
29819       Never-married            Sales  Other-relative  White    Male   
31110       Never-married    Other-service       Own-child  White    Male   
15732       Never-married            Sales       Own-child  Black  Female   
1674   Married-civ-spouse  Exec-managerial         Husband  White    Male   
15695  Married-civ-spouse   Prof-specialty         Husband  White    Male   

       capital.gain  capital.loss  hours.per.week native.country income  
22055             0             0              55  United-States  <=50K  
11786             0             0              40  United-States  <=50K  
27734             0             0              35  United-States  <=50K  
7661              0             0              40  United-States  <=50K  
25252             0             0              50  United-States  <=50K  
29819             0             0              40  United-States  <=50K  
31110             0             0              15              ?  <=50K  
15732             0             0              35  United-States  <=50K  
1674          99999             0              40  United-States   >50K  
15695             0             0              48  United-States   >50K

In [93]:
# Confirm which columns show presence of missing values in str format "?"
(df == "?").any()

age               False
workclass          True
fnlwgt            False
education         False
education.num     False
marital.status    False
occupation         True
relationship      False
race              False
sex               False
capital.gain      False
capital.loss      False
hours.per.week    False
native.country     True
income            False
dtype: bool

In [94]:
# Check for duplicates
df.duplicated().value_counts()

False    32537
True        24
Name: count, dtype: int64

In [95]:
# Drop duplicate rows
df.drop_duplicates(inplace=True)

In [96]:
# convert str missing values ("?") to NaN missing values for easier management.
df.replace("?", np.nan,inplace=True)

In [97]:
# Check missing values are now present with info.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32537 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32537 non-null  int64 
 1   workclass       30701 non-null  object
 2   fnlwgt          32537 non-null  int64 
 3   education       32537 non-null  object
 4   education.num   32537 non-null  int64 
 5   marital.status  32537 non-null  object
 6   occupation      30694 non-null  object
 7   relationship    32537 non-null  object
 8   race            32537 non-null  object
 9   sex             32537 non-null  object
 10  capital.gain    32537 non-null  int64 
 11  capital.loss    32537 non-null  int64 
 12  hours.per.week  32537 non-null  int64 
 13  native.country  31955 non-null  object
 14  income          32537 non-null  object
dtypes: int64(6), object(9)
memory usage: 4.0+ MB


In [98]:
# show amount of missing values and which columns they are in
df.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     582
income               0
dtype: int64

In [99]:
# check to see if all rows with missing values in workclass and occupation coincide.
df.loc[df["occupation"].isna() == df["workclass"].isna()]

age workclass  fnlwgt     education  education.num      marital.status  \
0       90       NaN   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66       NaN  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0                    NaN  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2                    NaN      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32530 rows x 15 columns]

In [100]:
(df["workclass"].isna() == df["occupation"].isna()).value_counts()

True     32530
False        7
Name: count, dtype: int64

In [101]:
# Check which rows don´t coincide
df.loc[df["occupation"].isna() != df["workclass"].isna()]

age     workclass  fnlwgt     education  education.num  \
8874    18  Never-worked  206359          10th              6   
13675   23  Never-worked  188535       7th-8th              4   
17089   17  Never-worked  237272          10th              6   
21934   18  Never-worked  157131          11th              7   
24483   20  Never-worked  462294  Some-college             10   
32331   30  Never-worked  176673       HS-grad              9   
32338   18  Never-worked  153663  Some-college             10   

           marital.status occupation   relationship   race     sex  \
8874        Never-married        NaN      Own-child  White    Male   
13675            Divorced        NaN  Not-in-family  White    Male   
17089       Never-married        NaN      Own-child  White    Male   
21934       Never-married        NaN      Own-child  White  Female   
24483       Never-married        NaN      Own-child  Black    Male   
32331  Married-civ-spouse        NaN           Wife  Black  Female   
32338       Never-married        NaN      Own-child  White    Male   

       capital.gain  capital.loss  hours.per.week native.country income  
8874              0             0              40  United-States  <=50K  
13675             0             0              35  United-States  <=50K  
17089             0             0              30  United-States  <=50K  
21934             0             0              10  United-States  <=50K  
24483             0             0              40  United-States  <=50K  
32331             0             0              40  United-States  <=50K  
32338             0             0               4  United-States  <=50K

In [102]:
# Check how many rows for the column "workclass" have the value "Never-worked".
df["workclass"].value_counts()

workclass
Private             22673
Self-emp-not-inc     2540
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [103]:
df["age"].unique()

array([90, 82, 66, 54, 41, 34, 38, 74, 68, 45, 52, 32, 51, 46, 57, 22, 37,
       29, 61, 21, 33, 49, 23, 59, 60, 63, 53, 44, 43, 71, 48, 73, 67, 40,
       50, 42, 39, 55, 47, 31, 58, 62, 36, 72, 78, 83, 26, 70, 27, 35, 81,
       65, 25, 28, 56, 69, 20, 30, 24, 64, 75, 19, 77, 80, 18, 17, 76, 79,
       88, 84, 85, 86, 87])

In [104]:
df["fnlwgt"].unique()

array([ 77053, 132870, 186061, ...,  34066,  84661, 257302],
      shape=(21648,))

In [105]:
df["workclass"].unique()

array([nan, 'Private', 'State-gov', 'Federal-gov', 'Self-emp-not-inc',
       'Self-emp-inc', 'Local-gov', 'Without-pay', 'Never-worked'],
      dtype=object)

In [106]:
df["occupation"].unique()

array([nan, 'Exec-managerial', 'Machine-op-inspct', 'Prof-specialty',
       'Other-service', 'Adm-clerical', 'Craft-repair',
       'Transport-moving', 'Handlers-cleaners', 'Sales',
       'Farming-fishing', 'Tech-support', 'Protective-serv',
       'Armed-Forces', 'Priv-house-serv'], dtype=object)

In [107]:
df["education"].unique()

array(['HS-grad', 'Some-college', '7th-8th', '10th', 'Doctorate',
       'Prof-school', 'Bachelors', 'Masters', '11th', 'Assoc-acdm',
       'Assoc-voc', '1st-4th', '5th-6th', '12th', '9th', 'Preschool'],
      dtype=object)

In [108]:
df["education.num"].unique()

array([ 9, 10,  4,  6, 16, 15, 13, 14,  7, 12, 11,  2,  3,  8,  5,  1])

In [109]:
df["marital.status"].unique()

array(['Widowed', 'Divorced', 'Separated', 'Never-married',
       'Married-civ-spouse', 'Married-spouse-absent', 'Married-AF-spouse'],
      dtype=object)

In [110]:
df["relationship"].unique()

array(['Not-in-family', 'Unmarried', 'Own-child', 'Other-relative',
       'Husband', 'Wife'], dtype=object)

In [111]:
df["race"].unique()

array(['White', 'Black', 'Asian-Pac-Islander', 'Other',
       'Amer-Indian-Eskimo'], dtype=object)

In [112]:
df["sex"].unique()

array(['Female', 'Male'], dtype=object)

In [113]:
df["hours.per.week"].unique()

array([40, 18, 45, 20, 60, 35, 55, 76, 50, 42, 25, 32, 90, 48, 15, 70, 52,
       72, 39,  6, 65, 12, 80, 67, 99, 30, 75, 26, 36, 10, 84, 38, 62, 44,
        8, 28, 59,  5, 24, 57, 34, 37, 46, 56, 41, 98, 43, 63,  1, 47, 68,
       54,  2, 16,  9,  3,  4, 33, 23, 22, 64, 51, 19, 58, 53, 96, 66, 21,
        7, 13, 27, 11, 14, 77, 31, 78, 49, 17, 85, 87, 88, 73, 89, 97, 94,
       29, 82, 86, 91, 81, 92, 61, 74, 95])

In [114]:
df["capital.gain"].unique()

array([    0, 99999, 41310, 34095, 27828, 25236, 25124, 22040, 20051,
       18481, 15831, 15024, 15020, 14344, 14084, 13550, 11678, 10605,
       10566, 10520,  9562,  9386,  8614,  7978,  7896,  7688,  7443,
        7430,  7298,  6849,  6767,  6723,  6514,  6497,  6418,  6360,
        6097,  5721,  5556,  5455,  5178,  5060,  5013,  4934,  4931,
        4865,  4787,  4687,  4650,  4508,  4416,  4386,  4101,  4064,
        3942,  3908,  3887,  3818,  3781,  3674,  3471,  3464,  3456,
        3432,  3418,  3411,  3325,  3273,  3137,  3103,  2993,  2977,
        2964,  2961,  2936,  2907,  2885,  2829,  2653,  2635,  2597,
        2580,  2538,  2463,  2414,  2407,  2387,  2354,  2346,  2329,
        2290,  2228,  2202,  2176,  2174,  2105,  2062,  2050,  2036,
        2009,  1848,  1831,  1797,  1639,  1506,  1471,  1455,  1424,
        1409,  1173,  1151,  1111,  1086,  1055,   991,   914,   594,
         401,   114])

In [115]:
df["capital.loss"].unique()

array([4356, 3900, 3770, 3683, 3004, 2824, 2754, 2603, 2559, 2547, 2489,
       2472, 2467, 2457, 2444, 2415, 2392, 2377, 2352, 2339, 2282, 2267,
       2258, 2246, 2238, 2231, 2206, 2205, 2201, 2179, 2174, 2163, 2149,
       2129, 2080, 2057, 2051, 2042, 2002, 2001, 1980, 1977, 1974, 1944,
       1902, 1887, 1876, 1848, 1844, 1825, 1816, 1762, 1755, 1741, 1740,
       1735, 1726, 1721, 1719, 1672, 1669, 1668, 1651, 1648, 1628, 1617,
       1602, 1594, 1590, 1579, 1573, 1564, 1539, 1504, 1485, 1411, 1408,
       1380, 1340, 1258, 1138, 1092,  974,  880,  810,  653,  625,  419,
        323,  213,  155,    0])

In [116]:
df["native.country"].unique()

array(['United-States', nan, 'Mexico', 'Greece', 'Vietnam', 'China',
       'Taiwan', 'India', 'Philippines', 'Trinadad&Tobago', 'Canada',
       'South', 'Holand-Netherlands', 'Puerto-Rico', 'Poland', 'Iran',
       'England', 'Germany', 'Italy', 'Japan', 'Hong', 'Honduras', 'Cuba',
       'Ireland', 'Cambodia', 'Peru', 'Nicaragua', 'Dominican-Republic',
       'Haiti', 'El-Salvador', 'Hungary', 'Columbia', 'Guatemala',
       'Jamaica', 'Ecuador', 'France', 'Yugoslavia', 'Scotland',
       'Portugal', 'Laos', 'Thailand', 'Outlying-US(Guam-USVI-etc)'],
      dtype=object)

In [117]:
df["income"].unique()

array(['<=50K', '>50K'], dtype=object)

In [118]:
# Create column "recode_never_worked" to show where we changed "Never-worked" to "unknown" in the column "workclass"
df["recode_never_worked"]  = df["workclass"] == "Never-worked"
df.loc[df["recode_never_worked"], "workclass"] = "unknown"

In [119]:
df.workclass.value_counts()

workclass
Private             22673
Self-emp-not-inc     2540
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
unknown                 7
Name: count, dtype: int64

In [120]:
# Create another column to show where we will fill the missing values with "unknown" in the columns "workclass","occupation" and "native.country".
df["had_missing_cat"] = (df[["workclass","occupation","native.country"]].isna().any(axis=1))

In [121]:
df.had_missing_cat.value_counts()

had_missing_cat
False    30139
True      2398
Name: count, dtype: int64

In [122]:
# Now fill the missing value with the value "unknown".
df["workclass"] = df["workclass"].fillna("unknown")
df["occupation"] = df["occupation"].fillna("unknown")
df["native.country"] = df["native.country"].fillna("unknown")

In [123]:
df.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90   unknown   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66   unknown  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0            unknown  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2            unknown      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  recode_never_worked  \
0          4356              40  United-States  <=50K                False   
1          4356              18  United-States  <=50K                False   
2          4356              40  United-States  <=50K                False   
3          3900              40  United-States  <=50K                False   
4          3900              40  United-States  <=50K                False   

   had_missing_cat  
0             True  
1            False  
2             True  
3            False  
4            False

In [124]:
# Check info to make sure no missing values left.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32537 entries, 0 to 32560
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   age                  32537 non-null  int64 
 1   workclass            32537 non-null  object
 2   fnlwgt               32537 non-null  int64 
 3   education            32537 non-null  object
 4   education.num        32537 non-null  int64 
 5   marital.status       32537 non-null  object
 6   occupation           32537 non-null  object
 7   relationship         32537 non-null  object
 8   race                 32537 non-null  object
 9   sex                  32537 non-null  object
 10  capital.gain         32537 non-null  int64 
 11  capital.loss         32537 non-null  int64 
 12  hours.per.week       32537 non-null  int64 
 13  native.country       32537 non-null  object
 14  income               32537 non-null  object
 15  recode_never_worked  32537 non-null  bool  
 16  had_missi

In [125]:
# Fix values "South" and "Hong" in the column "native.country"
df["native.country"] = df["native.country"].replace({"South":"South-Korea", "Hong":"Hong-Kong"})

In [126]:
# drop "fnlwgt" column.
df.drop(columns="fnlwgt",inplace = True)

In [127]:
# save cleaned df as a new csv named adult_clean ready to use for analysis.
df.to_csv("../data/adult_clean.csv", index=False)